image: maven:3.6.1

pipelines:
  default:
    - step:
        size: 2x
        caches:
          - gradle
          - gradlewrapper
          - maven
        script:
          - sed -i 's/^submission\.lookup\.ads\.apikey.*/submission.lookup.ads.apikey='$ADS_API_KEY'/g' dspace-api/src/test/data/dspaceFolder/config/local.cfg
          - ./dspace-api/src/test/data/dspaceFolder/bin/install_grobid.sh
          - mvn clean install license:check -Dmaven.test.skip=false -DskipITs=false -Pdspace-rest -P !assembly -B -V -Dsurefire.rerunFailingTestsCount=2

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper



